### PR TITLE
Bump Python => 3.7 min dependency for 1.3.0 to 

### PR DESCRIPTION
**Pull request by Leniox**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by tomMoral — APPROVED** [review]
LGTM!

Thx for the PR.

**Comment by ocefpaf** [comment]
@Leniox I made a commit to your branch to add the bot inspection but it seems that GH is not updating the PR.
Can you verify if you can add:

```
bot:
  inspection: update-grayskull
```

to the conda-forge.yml file?

**Comment by Leniox** [comment]
@ocefpaf Did that here https://github.com/conda-forge/joblib-feedstock/pull/38/commits/320fa173a28d2a00bb92a86056a95fddf02f1fcd

Although the commit still says unverified! Hmmm..

**Comment by tomMoral** [comment]
Not sure what is the problem here?

**Comment by tomMoral** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
