### PR TITLE
Joblib 0.15.0

### PR DESCRIPTION
**Pull request by ogrisel**
Alternative to #24 that sets the minimum python version explicitly.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ogrisel** [comment]
@conda-forge-admin, please rerender

**Comment by ogrisel** [comment]
This should be good to go @ocefpaf @jakirkham.

Please also consider  #23 if you want us to discharge you from the maintenance of this feedstock.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ogrisel** [comment]
Thanks @ocefpaf!

**Pull request merged**
